### ISSUE TITLE
Request for a document to be created for E-Series DE460C controller/expansion shelf replacement

### ISSUE THREAD

**Issue by JamieLove-Net2** [NetAppDocs/e-series#103]
### Page URL

https://docs.netapp.com/us-en/e-series/maintenance-e2800/index.html

### Page title

Maintain E2800 hardware

### Summary

The steps can be borrowed from this KB article: https://kb.netapp.com/on-prem/E-Series/Hardware-KBs/How_to_replace_an_E_Series_DE460c_controller_expansion_shelf

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-driley** [comment]
Thank you so much for your feedback. We'll review this enhancement request to the documentation and determine next steps.

**Comment by netapp-driley** [comment]
Thank you again for your feedback. 

After discussing with my team, would it be acceptable to add an expansion shelf replacement note with a link to the KB under the [E2800 maintenance section](https://docs.netapp.com/us-en/e-series/maintenance-e2800/controllers-overview-supertask-concept.html) as a short term solution?

This approach is to address the immediate need for the expansion shelf replacement information. Long term, we'd like to explore adding the expansion shelf replacement content under the user documentation with the E-Series engineering team's involvement, bandwidth permitting. 

Please let me know if you have any other feedback. 

Thanks again, 

Don Riley

**Comment by netapp-driley** [comment]
Added reference to KB article under the following location: 

- https://docs.netapp.com/us-en/e-series/maintenance-e2800/drives-60-supertask-task.html
