### ISSUE TITLE
16 vs 64GB DIMM configuration not addressed

### ISSUE THREAD

**Issue by jorimp** [NetAppDocs/e-series#18]
Page: [Replace controller in duplex configuration](https://docs.netapp.com/us-en/e-series/maintenance-e5700/controllers-duplex-supertask-task.html)

Nowhere in this controller replacement documentation does it mention swapping the DIMMs for 16 vs 64 GB memory configurations. I believe these instructions are supposed to be shipped with the hardware itself, but these steps should be included here as well.

**Comment by netapp-jsnyder** [comment]
Thanks @jorimp for your feedback. We'll investigate and update the topic accordingly.

**Comment by netapp-echurch** [comment]
A fix for this issue has been updated in the documentation and is live.
Thank you for your feedback, @jorimp!
