### ISSUE TITLE
need to update the doc so it have the block size requemts 

### ISSUE THREAD

**Issue by tfenton7** [NetAppDocs/e-series#23]
Page: [Perform NVMe over FC-specific tasks](https://docs.netapp.com/us-en/e-series/config-vmware/nmve-fc-perform-specific-task.html)

https://docs.netapp.com/us-en/e-series/pdfs/sidebar/VMware_express_configuration.pdf 

in our PDF guide we have the block size for ESXI host only supporting 512 block size 
For EF300 and EF600, you must set the block size to 512 bytes to ensure compatibility with
VMware. Refer to the SANtricity System Manager online help for more information on setting
a volume to 512 bytes 

this needs to be included in the online doc

**Comment by netapp-jsnyder** [comment]
Thanks @tfenton7. We will get this updated in the vmware online doc.

**Comment by netapp-driley** [comment]
Hi @tfenton7, 

Thank you so much for your feedback. Just to confirm the requested changes, you would like to see the EF600/EF300 512 block size note under the [Perform NVMe over FC-specific tasks page](https://docs.netapp.com/us-en/e-series/config-vmware/nmve-fc-perform-specific-task.html)? 

We currently have this note under the [Access SANtricity System Manager and use the Setup wizard ](https://docs.netapp.com/us-en/e-series/config-vmware/access-sam-setup-wizard-task.html) page of the VMware Express Guide (see below). If needed, I can repeat this note under the Perform NVMe over FC-specific tasks page.  
![image](https://user-images.githubusercontent.com/18422994/163836139-8f4443f1-3261-48b8-b998-43fbf91c567e.png)

Thank you, 

Don Riley

**Comment by netapp-driley** [comment]
512 block size note included under the [Perform NVMe over FC-specific tasks page](https://docs.netapp.com/us-en/e-series/config-vmware/nmve-fc-perform-specific-task.html)
