### ISSUE TITLE
Formatting 

### ISSUE THREAD

**Issue by scaleoutsean** [NetAppDocs/e-series#24]
Page: [Overview of the Storage Plugin for vCenter](https://docs.netapp.com/us-en/e-series/vcenter-plugin/san-spvc-ic-overview.html)

If this is is a title it should be properly formatted:

![image](https://user-images.githubusercontent.com/16622642/163513159-ad9effa2-394d-4271-83c0-f33b274b63e3.png)

**Comment by netapp-jsnyder** [comment]
Thanks for catching this @scaleoutsean. Will get this fixed.

**Comment by netapp-jsnyder** [comment]
@scaleoutsean I updated the public site with the corrected graphic.
[Overview of the Storage Plugin for vCenter](https://docs.netapp.com/us-en/e-series/vcenter-plugin/san-spvc-ic-overview.html)
