### ISSUE TITLE
Customer found use of term 'IPoIB' confusing here and I'm seeking to change it to something less confusing

### ISSUE THREAD

**Issue by claytons** [NetAppDocs/e-series#33]
Page: [Configure networking for storage attached hosts](https://docs.netapp.com/us-en/e-series/config-linux/iser-ib-configure-network-attached-hosts-task.html)

We had a customer complain about the usage of the term IPoIB in this documentation. They found it frustrating and confusing. I attempted to remove it and added language that should be more straight forward with this change (https://github.com/claytons/e-series/commit/a562f3bd94171922819b64921e13764fedca46c7), but I'm thinking I didn't submit it correctly, so am trying this approach instead. 

Can someone help me out?

Regards,
-Clayto
![iSER_DocumentationChange](https://user-images.githubusercontent.com/9013469/170523667-17c6dd08-8a69-48c2-bf90-8dbdd36bf33a.JPG)
n

**Comment by netapp-jsnyder** [comment]
Thank-you @claytons. We've updated the topic with these changes.
