### ISSUE TITLE
E2800 without onboard ports and new HIC X-56034-00 or X-56035-00 

### ISSUE THREAD

**Issue by Caschtor** [NetAppDocs/e-series#41]
Page: [Requirements for changing E2800 host port protocol](https://docs.netapp.com/us-en/e-series/maintenance-e2800/hpp-overview-supertask-concept.html)
Currently new E2800 shipments comes without onboard ports. For host connection HIC X-56034-00 ( FC ) or X-56035-00 ( 10Gb/25Gb ) is available. According to https://hwu.netapp.com/ the HIC X-56034-00 ( FC ) only supports FCP and X-56035-00 ( 10Gb/25Gb ) only iSCSI. Although the unified SFP X-48895-00-R6 are available for both HIC a change of host port protocol seems to be not possible. I'am no technician so this needs additional verification. I only got one customer reply about this issue and they were not able to change host port protocol from FC to iSCSI for X-56034-00.

**Comment by netapp-echurch** [comment]
Hello @Caschtor!
I'm Beth Church the E-Series hardware writer!
I have picked up this issue and will begin work on it as soon as I am able.
I will post updates here for you to follow.

Thank you for your time!

Beth
