### ISSUE TITLE
Misformatted output

### ISSUE THREAD

**Issue by scaleoutsean** [NetAppDocs/e-series#44]
Page: [Access NVMe volumes for physical NVMe device targets](https://docs.netapp.com/us-en/e-series/config-linux/nvme-ib-access-physical-targets-concept.html)

Current:

```
# ls /dev/disk/by-id/ -l lrwxrwxrwx 1 root root 13 Oct 18 15:14
nvme-eui.0000320f5cad32cf00a0980000af4112 -> ../../nvme0n1
```

Should be:

```
# ls /dev/disk/by-id/ -l 
lrwxrwxrwx 1 root root 13 Oct 18 15:14 nvme-eui.0000320f5cad32cf00a0980000af4112 -> ../../nvme0n1
```

**Comment by netapp-driley** [comment]
Hi Sean - Thank you so much for your feedback. We'll look into this item and keep you posted once the changes are published. 

Thanks!

**Comment by netapp-driley** [comment]
FYI, ran this item by E-Series engineering and they are okay with this change. This change should be available in our next maintenance release. 

If you have any questions, please let me know.

**Comment by netapp-driley** [comment]
Change will be available in next published release of the Linux Express Guide.
