### ISSUE TITLE
Use of rc.local on RHEL 8

### ISSUE THREAD

**Issue by scaleoutsean** [NetAppDocs/e-series#45]
Page: [Configure subnet manager](https://docs.netapp.com/us-en/e-series/config-linux/nvme-ib-configure-subnet-manager-task.html)

> Add the following two lines to /etc/rc.d/rc.local

From rc.local:

```
# THIS FILE IS ADDED FOR COMPATIBILITY PURPOSES

It is highly advisable to create own systemd services or udev rules
to run scripts during boot instead of using this file.
```

The reco fo rc.local should be replaced by an example of a systemd service (one-shot script that does the same thing as rc.local used to do on old RHEL releases).

**Comment by netapp-driley** [comment]
Hi Sean - Thank you so much for your feedback. We'll look into this item and keep you posted once the changes are available. 

Thanks!

**Comment by netapp-driley** [comment]
Update - I ran this item by the E-Series engineering team and they need additional time to investigate the proposed change. I'll keep you posted on their findings.

**Comment by netapp-driley** [comment]
Hi Sean - This procedure will be updated and published in the next maintenance release. If you need any further assistance, please let us know!

Thanks!
