### ISSUE TITLE
Steps under external management are not clear / complete

### ISSUE THREAD

**Issue by ahmadm-netapp** [NetAppDocs/e-series#47]
Page: [Unlock drives](https://docs.netapp.com/us-en/e-series/upgrade-controllers/upgrade-unlock-drives-task.html)

Looking at this condition "External key management, all drives locked, you are not able to transition to internal key management temporarily for the controller replacement." from page https://docs.netapp.com/us-en/e-series/upgrade-controllers/prepare-upgrade-controllers-task.html, I don't follow how the external management steps in this page are addressing it. Few comments below:

1. Steps to configure external key manager are using a direct connection from laptop to controller. There is no mention of needing to configure a network port on controller. There is no direction here about DHCP or if DHCP is not available, when does customer switch to connecting controller to customer's network so it is able to contact the key server. How would controller be able to reach key server? 
 
2. Step 3 says to import key, but that doesn't sound to be valid because our ultimate goal in this procedure is to connect to the external key server.

Please review the steps and confirm if they are successful in QA.

**Comment by netapp-jolieg** [comment]
Thank you for your feedback. We are working with Engineering to determine the correct procedures, and should have it completed for our next release in October.

**Comment by netapp-jolieg** [comment]
Hi,
We worked with Development to update the Prepare Controllers and Unlock Drives topics for the upcoming 11.74 release. 
You can view the drafts here at our internal repository (you must be logged into our VPN):
- https://review.docs.netapp.com/us-en/e-series_1174-releasebranch/upgrade-controllers/prepare-upgrade-controllers-task.html
- https://review.docs.netapp.com/us-en/e-series_1174-releasebranch/upgrade-controllers/upgrade-unlock-drives-task.html
If you have further questions, you can contact me over email and I can connect you with Development.
