### ISSUE TITLE
Provide complete list of packages that need to be installed for iSER to work

### ISSUE THREAD

**Issue by scaleoutsean** [NetAppDocs/e-series#49]
Page: [Configure subnet manager](https://docs.netapp.com/us-en/e-series/config-linux/iser-ib-configure-subnet-manager-task.html)

This part:

- Install the opensm package on any hosts that will be running the subnet manager.
- Use the ibstat -p command to find GUID0 and GUID1 of the HBA ports. For example

Where is `ibstat` coming from? 

In some sections (such as iSCSI) there's a reminder to verify the presence of certain packages. In iSER section there's nothing but `opensm`.

And in iSER section, under Configure Networking, there are many poorly formatted rows with an unnecessary `\`.

```
iscsiadm -m node --target <Target IQN\> -I iface-ib0 -p <Target Port IP\> -l
```

**Comment by netapp-driley** [comment]
Hi Sean - Thank you so much for your feedback. We will review this content and revise as needed. I will keep you posted once the revisions are available for publication. 

If you have any other questions or concerns, please let me know. 

Thanks!

**Comment by netapp-driley** [comment]
Hi - Sean the Configure Subnet Manager topic under the Linux Express Guide will be updated to clarify the ibstat step. This revision will be available in the next maintenance release of the SANtricity publications.  If you have any other comments or questions, please let us know.
