### ISSUE TITLE
Document that ro and rw are legacy roles

### ISSUE THREAD

**Issue by scaleoutsean** [NetAppDocs/e-series#57]
Page: [Manage user access in Web Services Proxy](https://docs.netapp.com/us-en/e-series/web-services-proxy/access-intro-concept.html)

This WP mentions `ro` and `rw` are legacy roles that don't even work on newer arrays. The docs do not.

https://www.netapp.com/media/56663-wp-7344.pdf

**Comment by netapp-jolieg** [comment]
Response from Dev -- "We no longer use ro/rw roles with webservices. Any reference to these roles should be removed."

I have removed any references to ro/rw. The changes will be included in our next content release.
