### ISSUE TITLE
Possible typo

### ISSUE THREAD

**Issue by scaleoutsean** [NetAppDocs/e-series#58]
Page: [Manage AutoSupport using Web Services Proxy](https://docs.netapp.com/us-en/e-series/web-services-proxy/asup-intro-concept.html)

```
Locate the lines for <asupdata enabled="(Boolean)" timestamp⇒
```

I haven't seen these files but that `⇒` looks odd.

**Comment by netapp-jolieg** [comment]
Thank you for your feedback.
We will check that content with the Dev team.

**Comment by netapp-jolieg** [comment]
Response from Dev -- "The symbol in question is actually a equal sign with a greater then sign. I would change it to this < asupdata enable=”Boolean_value” timestamp=”timestamp” > to help with the confusion."

I have updated the content. It will be incorporated into the next content release.
