### ISSUE TITLE
Correct SANtricity OS version from 11.07.2 to 11.70.2

### ISSUE THREAD

**Issue by ahmadm-netapp** [NetAppDocs/e-series#61]
Page: [Drive shelf cabling](https://docs.netapp.com/us-en/e-series/install-hw-cabling/driveshelf-cable-task.html)

The E-Series SANtricity OS version is incorrect.

Current Statement:
IOM12B modules are only supported on SANtricity OS 11.07.2 onward.

but it should be: 
IOM12B modules are only supported on SANtricity OS 11.70.2 onward.

**Comment by netapp-jsnyder** [comment]
@ahmadm-netapp Thanks for catching this. We will get this topic updated.

**Comment by netapp-driley** [comment]
The "11.07.2" typo has been fixed and the [change published](https://docs.netapp.com/us-en/e-series/install-hw-cabling/driveshelf-cable-task.html). 
![image](https://user-images.githubusercontent.com/18422994/208758416-57797d7a-93f3-4fd8-9a04-52796dff89d4.png)
