### ISSUE TITLE
possible mismatch on the Feature Activation Code on the step 1: Obtain the feature pack key

### ISSUE THREAD

**Issue by Jhon-Nieto-Netapp** [NetAppDocs/e-series#62]
Page: [Change host protocol for an EF300 or EF600](https://docs.netapp.com/us-en/e-series/maintenance-ef600/hpp-change-supertask-task.html)
On the technical case 2009403250 the customer was trying to change the Controller submodel ID from 443 to 448.
On the documentation it shows that the Feature Activation Code for this is 7HZ-EB4-ZHAYW, so the customer generated the file 952143002553-SWFCtoNVMeFCorRoCEEF600.key, which failed to complete the change.
After trying some options we noticed that the file name shows the transition on an opposite way "FC to NVMeFCorRoCE".
So we tried then using the Feature Activation Code JHX-UB4-ZGTP1 which on the document is the one for the conversion 448 to 443.
We got the file 952143002553-SWNVMeFCorRoCEtoFCEF600.key, and it worked, the customer was able to change the feature pack.

So on this sample we may have the Feature Activation Codes backwards, which should be changed and if possible, test the other codes to confirm those are the right ones.

**Comment by netapp-driley** [comment]
Please leave this item open. The issue will be resolved in the upcoming E-Series release.

**Comment by netapp-driley** [comment]
This correction will be available with the publication of the latest E-Series release documentation.
