### ISSUE TITLE
ifup and ifdown is missing and depricated in RHEL8 and later

### ISSUE THREAD

**Issue by peterupton** [NetAppDocs/e-series#64]
Page: [Set up NVMe over InfiniBand on the host side](https://docs.netapp.com/us-en/e-series/config-linux/nvme-ib-setup-host-side-task.html)

Step 6 requires running `ifup`, but this is not instaled by default in RHEL 8 and later.
See [Considerations in Adopting RHEL 8](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/considerations_in_adopting_rhel_8/networking_considerations-in-adopting-rhel-8), section 9.11 "Legacy network scripts support".

**Comment by netapp-driley** [comment]
HI Peter - Thank you so much for your feedback. We will revise the context for running ifup under this procedure. I will keep you updated once the revision is published. If you have any other questions or concerns, please let me know. 

Thanks again, 

Don Riley
