### ISSUE TITLE
SFP Maintenance Page 

### ISSUE THREAD

**Issue by hcameron25** [NetAppDocs/e-series#67]
Page: [E-Series systems documentation](https://docs.netapp.com/us-en/e-series/index.html)

Customer requested a SFP Maintenance Page about how to handle SFP Maintenance

**Comment by netapp-driley** [comment]
Please leave this item open. The issue will be resolved in the upcoming E-Series release.

**Comment by ntap-bmegan** [comment]
@netapp-driley - What is the status of this issue?

**Comment by netapp-driley** [comment]
This item is an enhancement request to the documentation. I'll need to discuss with E-Series engineering about what information we'd wanted to add to the documentation regarding SFP maintenance. I'll close this item and if any corrections to the existing SFP content in the documentation is needed, please feel free to submit a new issue. 

Thanks, 

Don Riley
