### ISSUE TITLE
"feature pack submodel ID" different in Storage Array Profile

### ISSUE THREAD

**Issue by alonsod-netapp** [NetAppDocs/e-series#71]
Page: [Change host protocol for E2800](https://docs.netapp.com/us-en/e-series/maintenance-e2800/hpp-change-host-protocol-task.html)

"Step 2: Obtain the feature pack" section, step 2b says to type "feature pack submodel ID" in the **Find** box of storage array profile.

That search will not work because in the Storage Array Profile of the system I used, which was running Predator.1 code, the ID was actually labelled "Feature pack sub-model ID", there was a hyphen between "sub" and "model".
![Sub-model](https://user-images.githubusercontent.com/118284470/213205743-1c37e54c-f315-4bb7-96f5-22b2bd170fba.jpg)

**Comment by netapp-driley** [comment]
This correction will be available with the publication of the latest E-Series release documentation.
