### ISSUE TITLE
escape slashes display in search results

### ISSUE THREAD

**Issue by ntap-bmegan** [NetAppDocs/e-series#73]
Page: [Verify the Linux configuration is supported](https://docs.netapp.com/us-en/e-series/config-linux/iser-ib-verify-linux-config-support-task.html)

This is also true for other topics. 

![image](https://user-images.githubusercontent.com/56453501/220752762-6899bd81-3984-4bdb-82ad-7cb11ac4c67b.png)

If you quote the summary you should be able to remove the slashes.

**Comment by netapp-driley** [comment]
This correction will be available with the publication of the latest E-Series release documentation.
