### ISSUE TITLE
miss allocation of number

### ISSUE THREAD

**Issue by osakanataro** [NetAppDocs/e-series#79]
Page: [Configure the multipath software](https://docs.netapp.com/us-en/e-series/config-linux/iscsi-configure-multipath-software-task.html)

please re-numbered "Reboot the host."

**Comment by netapp-driley** [comment]
Hi osakanataro - Thank you so much for your feedback. We'll make sure to correct the formatting for this and have the revision available as soon as possible. If you have any other feedback, please let us know. 

Thanks again, 

Don Riley

**Comment by netapp-driley** [comment]
This correction will be available with the publication of the latest E-Series release documentation.
