### ISSUE TITLE
Wrong target IP address

### ISSUE THREAD

**Issue by samgrcia** [NetAppDocs/e-series#82]
Page: [Découverte et connexion au stockage depuis l’hôte](https://docs.netapp.com/fr-fr/e-series/config-linux/nvme-ib-discover-connect-storage-host-task.html)

The target IP address should be different from the host IP address in the command : 

```
# nvme discover -t rdma -a 10.10.10.100
```

**Comment by netapp-driley** [comment]
This correction will be available in the next published release.
