### ISSUE TITLE
No submodel ID for iSCSI is listed 

### ISSUE THREAD

**Issue by alonsod-netapp** [NetAppDocs/e-series#83]
Page: [Change host protocol for an EF300 or EF600](https://docs.netapp.com/us-en/e-series/maintenance-ef600/hpp-change-supertask-task.html)

Looking at the table under step 3 that lists beginning and ending SMIDs, there are no SMIDs for iSCSI.

Both the EF300 and EF600 support the 25Gb iSCSI HIC so there should be SMIDs that correspond to iSCSI configuration for EF300/EF600.

**Comment by netapp-driley** [comment]
Hello, 

Thank you so much for your feedback. I will look into this item and update the documentation accordingly. If you have any other feedback, please let me know. 

Thanks, 

Don Riley

**Comment by netapp-driley** [comment]
The correction for this item will be published with the next E-Series release.
