### ISSUE TITLE
SSE Feedback on Replace E5700 drive drawer (60-drive)

### ISSUE THREAD

**Issue by tullynet** [NetAppDocs/e-series#84]
### Page URL

https://docs.netapp.com/us-en/e-series/maintenance-e5700/drives-drawer-supertask-task.html

### Page title

Replace E5700 drive drawer (60-drive)

### Summary

Under Step 2: Remove cable chains, sub step 3, the photo showing the cable chain connection appears to be labeled incorrectly.  

It's currently labeled:
(1) Vertical connector (connected to midplane)

(2) Cable chain

(3) Horizontal connector (connected to drawer)

It should be:
(1) Cable chain

(2) Vertical connector (connected to midplane)

(3) Horizontal connector (connected to drawer)

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-driley** [comment]
Hello, 

Thank you so much for your feedback. I will look into this item and update the documentation accordingly. If you have any other feedback, please let me know. 

Thanks, 

Don Riley

**Comment by netapp-driley** [comment]
The revision for this item will be available in the next publication of the E-Series documentation.
