### ISSUE TITLE
on the install poster, can we change the PDF to include subnet masks

### ISSUE THREAD

**Issue by ericd-netapp** [NetAppDocs/e-series#88]
### Page URL

https://docs.netapp.com/us-en/e-series/install-hw-e2800-e5700/index.html

### Page title

Install and set up E2800 and E5700 storage systems

### Summary

we had a customer unable to connect to an e-series controller becasue the subnet mask wasn't specified in the instructions.

please refer to this KB

https://kb.netapp.com/onprem/E-Series/Hardware/What_are_the_Default_Management_Port_IP_addresses_available_on_E-Series_controllers%3F

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-driley** [comment]
Hi Eric, 

Thank you so much for your feedback. We will look into this item and revise the content as needed. If you have any other feedback, please let us know. 

Thanks again, 

Don Riley

**Comment by netapp-driley** [comment]
The default subnet mask will be reincorporated into the ISI. The default subnet mask was originally included in the ISI but removed from recent editions. This revision will be available in the latest publication release.
