### ISSUE TITLE
Change in the ping command flag

### ISSUE THREAD

**Issue by beemerdnetapp** [NetAppDocs/e-series#97]
### Page URL

https://docs.netapp.com/us-en/e-series/config-windows/iscsi-perform-specific-task.html

### Page title

Perform iSCSI-specific tasks

### Summary

For step 5 the ping command needs to be ping -S not -s
Per the ping command: -S srcaddr     Source address to use

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-driley** [comment]
This issue is resolved and will be available in the next published SANtricity release.
